-- ─────────────────────────────────────────────────────────────────────────────
-- Tabla CITAS_TALLER — agenda de citas del taller (CRM + portal web)
-- Ejecutar UNA sola vez en el SQL Editor de Supabase.
--
-- NOTA: la tabla no existía en la base de datos (el código la usaba pero la
-- migración original nunca se corrió). Este script la crea completa, con todas
-- las columnas que usa el backend, incluidas las de las citas agendadas desde
-- la web (nombre, correo, teléfono, placa y modelo del cliente que aún no está
-- registrado como cliente formal).
-- ─────────────────────────────────────────────────────────────────────────────

create table if not exists citas_taller (
  id                   bigint generated by default as identity primary key,

  -- Vínculos opcionales al CRM (las citas web llegan sin cliente/vehículo aún)
  cliente_id           bigint,
  vehiculo_id          bigint,
  mantenimiento_id     bigint,

  -- Datos de la cita
  fecha                date not null,
  hora                 text default '09:00',
  tipo_servicio        text,
  descripcion          text,
  origen               text default 'CRM',        -- 'CRM' | 'WEB'
  notas                text,
  estado               text default 'PENDIENTE',  -- PENDIENTE | CONFIRMADA | COMPLETADA | CANCELADA | NO_ASISTIO
  recordatorio_enviado boolean default false,

  -- Datos de contacto de la cita agendada desde la WEB (cliente aún no registrado)
  nombre_contacto      text,
  email_contacto       text,
  telefono_contacto    text,
  placa_texto          text,
  modelo_texto         text,

  created_at           timestamptz default now(),
  updated_at           timestamptz
);

-- Por si la tabla ya existía de forma parcial: agrega columnas faltantes.
alter table citas_taller
  add column if not exists cliente_id           bigint,
  add column if not exists vehiculo_id          bigint,
  add column if not exists mantenimiento_id     bigint,
  add column if not exists hora                 text default '09:00',
  add column if not exists tipo_servicio        text,
  add column if not exists descripcion          text,
  add column if not exists origen               text default 'CRM',
  add column if not exists notas                text,
  add column if not exists estado               text default 'PENDIENTE',
  add column if not exists recordatorio_enviado boolean default false,
  add column if not exists nombre_contacto      text,
  add column if not exists email_contacto       text,
  add column if not exists telefono_contacto    text,
  add column if not exists placa_texto          text,
  add column if not exists modelo_texto         text,
  add column if not exists created_at           timestamptz default now(),
  add column if not exists updated_at           timestamptz;

-- Índices para filtrar rápido la agenda
create index if not exists idx_citas_fecha  on citas_taller (fecha);
create index if not exists idx_citas_estado on citas_taller (estado);
create index if not exists idx_citas_origen on citas_taller (origen);
