-- ═══════════════════════════════════════════════════════════════════
-- MIGRACIÓN V21 — Citas del Taller + Ficha 360 + Recordatorios
-- Ejecutar en Supabase (SQL Editor)
--
-- ⚠️ NOTA: la tabla "citas" existente pertenece al CRM CLÍNICO
-- (pacientes/médicos) y NO se toca. El taller usa su propia tabla:
-- "citas_taller".
-- ═══════════════════════════════════════════════════════════════════

-- ── 1. CITAS DEL TALLER ──────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS citas_taller (
  id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cliente_id           INTEGER,
  vehiculo_id          BIGINT,
  mantenimiento_id     INTEGER,                  -- plan de mantenimiento que la originó (opcional)
  fecha                DATE NOT NULL,
  hora                 TEXT DEFAULT '09:00',
  tipo_servicio        TEXT,                     -- CAMBIO_ACEITE, FRENOS, DIAGNOSTICO, etc.
  descripcion          TEXT,
  estado               TEXT DEFAULT 'PENDIENTE', -- PENDIENTE | CONFIRMADA | COMPLETADA | CANCELADA | NO_ASISTIO
  origen               TEXT DEFAULT 'CRM',       -- CRM | CLIENTE | RECORDATORIO
  recordatorio_enviado BOOLEAN DEFAULT FALSE,
  notas                TEXT,
  created_at           TIMESTAMPTZ DEFAULT NOW(),
  updated_at           TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_citas_taller_fecha   ON citas_taller(fecha);
CREATE INDEX IF NOT EXISTS idx_citas_taller_cliente ON citas_taller(cliente_id);
CREATE INDEX IF NOT EXISTS idx_citas_taller_estado  ON citas_taller(estado);

-- ── 2. INTERACCIONES CON EL CLIENTE (la "memoria" del CRM) ──────────
-- Cada contacto queda registrado: WhatsApp enviado, llamada, nota, etc.
CREATE TABLE IF NOT EXISTS cliente_interacciones (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cliente_id     INTEGER NOT NULL,
  vehiculo_id    BIGINT,
  tipo           TEXT DEFAULT 'NOTA',   -- WHATSAPP | LLAMADA | EMAIL | VISITA | NOTA | SISTEMA
  descripcion    TEXT,
  referencia     TEXT,                  -- ej: 'recordatorio-mant:12', 'cita:5', 'seguimiento:340'
  usuario_nombre TEXT,
  created_at     TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_interacciones_cliente ON cliente_interacciones(cliente_id);
CREATE INDEX IF NOT EXISTS idx_interacciones_ref     ON cliente_interacciones(referencia);

-- ── 3. MEMORIA EN LA FICHA DEL CLIENTE (tabla clientes del taller) ──
ALTER TABLE clientes ADD COLUMN IF NOT EXISTS notas                TEXT;
ALTER TABLE clientes ADD COLUMN IF NOT EXISTS preferencia_contacto TEXT; -- WHATSAPP | LLAMADA | EMAIL
